### ISSUE TITLE
watch.sh errors

### ISSUE THREAD

**Issue by stegmannc** [dwalldorf/owTracker#27]
> ./bin/watch.sh
> DEPRECATION WARNING:
> Sass 3.5 will no longer support Ruby 1.9.3.
> Please upgrade to Ruby 2.0.0 or greater as soon as possible.
> 
> > > Sass is watching for changes. Press Ctrl-C to stop.
> > >   directory web/static/css
> > > fs.js:892
> > >   return binding.stat(pathModule._makeLong(path));
> > >                  ^

Error: ENOENT: no such file or directory, stat '/usr/share/nginx/owt/.sass-cache/521c27602833bac3396b097860653bde92ba14a6/tables.scssc20160529-20684-1sxpm6g'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at visitDirectory (/usr/share/nginx/owt/node_modules/ntypescript/bin/ntypescript.js:2070:44)
    at visitDirectory (/usr/share/nginx/owt/node_modules/ntypescript/bin/ntypescript.js:2083:25)
    at visitDirectory (/usr/share/nginx/owt/node_modules/ntypescript/bin/ntypescript.js:2083:25)
    at Object.readDirectory (/usr/share/nginx/owt/node_modules/ntypescript/bin/ntypescript.js:2056:17)
    at getFileNames (/usr/share/nginx/owt/node_modules/ntypescript/bin/ntypescript.js:33129:56)
    at Object.parseJsonConfigFileContent (/usr/share/nginx/owt/node_modules/ntypescript/bin/ntypescript.js:33091:25)
    at parseConfigFile (/usr/share/nginx/owt/node_modules/ntypescript/bin/ntypescript.js:44649:40)
    at performCompilation (/usr/share/nginx/owt/node_modules/ntypescript/bin/ntypescript.js:44676:45)
      write web/static/css/style.css
      write web/static/css/style.css.map
[Listen warning]:
  Listen will be polling for changes. Learn more at https://github.com/guard/listen#polling-fallback.

**Comment by dwalldorf** [comment]
caused by #26
